development:
  allow_prefix_called_number: true
  sip_require_approval: false

test:
  allow_prefix_called_number: false
  sip_require_approval: true

production:
  allow_prefix_called_number: false
  sip_require_approval: false