default: &default
  # SMTP Mandrill config
  SETTINGS__SMTP__ADDRESS: address
  SETTINGS__SMTP__DOMAIN: domain
  SETTINGS__SMTP__USER_NAME: username
  SETTINGS__SMTP__PASSWORD: password
  SETTINGS__SMTP__HOST: host
  SETTINGS__SMTP__DEFAULT_FROM: notifications@example.org
  MAILER_SENDER: notifications@example.org
  EXCEPTION_RECIPIENTS: amind@instedd.org
  SETTINGS__SMTP__PORT: 587

development:

production:
